#include <jni.h>
#include "jni-base.h"

int RETURNVAL_CLASS = 0;
int FUNCTION_CLASS = 1;
int IMAGEDATA_CLASS = 2;
int TOKEN_CLASS = 3;
int PROXIMITYINFO_CLASS = 4;
int ARRAYLIST_CLASS = 5;
int CAMERA_CLASS = 6;
jclass CLASSES[7];

int ARRAYLIST_INIT = 0;
int ARRAYLIST_ADD = 1;
int TOKEN_GETTEXTLENGTH = 2;
int TOKEN_CHARAT = 3;
int IMAGEDATA_INIT = 4;
jmethodID METHODS[5];

int RETURNVAL_VALUE_FIELD_IDX = 0;
int RETURNVAL_TEXT_FIELD_IDX = 1;
int RETURNVAL_ISNULL_FIELD_IDX = 2;
int TOKEN_COLUMN_FIELD_IDX = 3;
int TOKEN_PRIORITY_FIELD_IDX = 4;
int TOKEN_TYPE_FIELD_IDX = 5;
jfieldID FIELDS[6];
