#include <jni.h>
#include "jni-base.h"

int ARRAYLIST_CLASS = 0;
int CAMERA_CLASS = 1;
jclass CLASSES[2];

int ARRAYLIST_INIT = 0;
int ARRAYLIST_ADD = 1;
jmethodID METHODS[2];

/*
int RETURNVAL_VALUE_FIELD_IDX = 0;
int RETURNVAL_TEXT_FIELD_IDX = 1;
int RETURNVAL_ISNULL_FIELD_IDX = 2;
int TOKEN_COLUMN_FIELD_IDX = 3;
int TOKEN_PRIORITY_FIELD_IDX = 4;
int TOKEN_TYPE_FIELD_IDX = 5;
jfieldID FIELDS[6];
*/
